blog1gram <- as.data.frame(blog1gram)
blog2gram <- as.data.frame(blog2gram)
blog3gram <- as.data.frame(blog3gram)
news1gram <- as.data.frame(news1gram)
news2gram <- as.data.frame(news2gram)
news3gram <- as.data.frame(news3gram)
twit1gram <- as.data.frame(twit1gram)
twit2gram <- as.data.frame(twit2gram)
twit3gram <- as.data.frame(twit3gram)

colnames(blog1gram) <- c("gram1", "freq")
colnames(news1gram) <- c("gram1", "freq")
colnames(twit1gram) <- c("gram1", "freq")
colnames(blog2gram) <- c("gram2", "freq")
colnames(news2gram) <- c("gram2", "freq")
colnames(twit2gram) <- c("gram2", "freq")
colnames(blog3gram) <- c("gram3", "freq")
colnames(news3gram) <- c("gram3", "freq")
colnames(twit3gram) <- c("gram3", "freq")

blog1gram$gram1 <- as.character(blog1gram$gram1)
blog2gram$gram2 <- as.character(blog2gram$gram2)
blog3gram$gram3 <- as.character(blog3gram$gram3)
news1gram$gram1 <- as.character(news1gram$gram1)
news2gram$gram2 <- as.character(news2gram$gram2)
news3gram$gram3 <- as.character(news3gram$gram3)
twit1gram$gram1 <- as.character(twit1gram$gram1)
twit2gram$gram2 <- as.character(twit2gram$gram2)
twit3gram$gram3 <- as.character(twit3gram$gram3)

wordfreq <- union(blog1gram, news1gram, twit1gram, by = "gram1")
wordfreq2 <- union(blog2gram, news2gram, twit2gram, by = "gram2")
wordfreq3 <- union(blog3gram, news3gram, twit3gram, by = "gram3")

wordfreq <- wordfreq %>% mutate(freq = freq1 + freq2 + freq3)
wordfreq2 <- wordfreq2 %>% mutate(freq = freq4 + freq5 + freq6)
wordfreq3 <- wordfreq3 %>% mutate(freq = freq7 + freq8 + freq9)

gram2t <- wordfreq2$gram2
gram2t <- gram2t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=2)
wordfreq2 <- wordfreq2 %>% mutate(gram2a = gram2t[,1], gram2b = gram2t[,2])
gram3t <- wordfreq3$gram3
gram3t <- gram3t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=3)
wordfreq3 <- wordfreq3 %>% mutate(gram3a = gram3t[,1], gram3b = gram3t[,2], gram3c = gram3t[,3])

save(data, file = "base.Rdata")