blog1gram <- as.data.frame(blog1gram)
blog2gram <- as.data.frame(blog2gram)
blog3gram <- as.data.frame(blog3gram)
news1gram <- as.data.frame(news1gram)
news2gram <- as.data.frame(news2gram)
news3gram <- as.data.frame(news3gram)
twit1gram <- as.data.frame(twit1gram)
twit2gram <- as.data.frame(twit2gram)
twit3gram <- as.data.frame(twit3gram)

blog1gram$blog1gram <- as.character(blog1gram$blog1gram)
gram2t <- as.character(blog2gram$blog2gram)
gram2t <- gram2t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=2)
blog2gram <- blog2gram %>% mutate(gram2a = gram2t[,1], gram2b = gram2t[,2])
gram3t <- as.character(blog3gram$blog3gram)
gram3t <- gram3t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=3)
blog3gram <- blog3gram %>% mutate(gram3a = gram3t[,1], gram3b = gram3t[,2], gram3c = gram3t[,3])

news1gram$news1gram <- as.character(news1gram$news1gram)
gram2t <- as.character(news2gram$news2gram)
gram2t <- gram2t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=2)
news2gram <- news2gram %>% mutate(gram2a = gram2t[,1], gram2b = gram2t[,2])
gram3t <- as.character(news3gram$news3gram)
gram3t <- gram3t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=3)
news3gram <- news3gram %>% mutate(gram3a = gram3t[,1], gram3b = gram3t[,2], gram3c = gram3t[,3])

twit1gram$twit1gram <- as.character(twit1gram$twit1gram)
gram2t <- as.character(twit2gram$twit2gram)
gram2t <- gram2t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=2)
twit2gram <- twit2gram %>% mutate(gram2a = gram2t[,1], gram2b = gram2t[,2])
gram3t <- as.character(twit3gram$twit3gram)
gram3t <- gram3t %>% strsplit(split = " ") %>% unlist() %>% matrix(byrow = TRUE, ncol=3)
twit3gram <- twit3gram %>% mutate(gram3a = gram3t[,1], gram3b = gram3t[,2], gram3c = gram3t[,3])


save(data, file = "base.Rdata")
